
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Mon Nov 14 01:11:07 CST 2016
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int GREATERTHAN = 24;
  public static final int ASTERISK = 29;
  public static final int EQUALS = 13;
  public static final int SLASH = 30;
  public static final int UMINUS = 17;
  public static final int EQUALSEQUALS = 26;
  public static final int BARBAR = 19;
  public static final int INT = 33;
  public static final int MINUS = 21;
  public static final int CLOSEPAREN = 8;
  public static final int LESSTHANEQUALS = 23;
  public static final int SEMICOLON = 14;
  public static final int OPENPAREN = 7;
  public static final int LESSTHAN = 22;
  public static final int BOOL = 32;
  public static final int COMMA = 16;
  public static final int PLUS = 20;
  public static final int IF = 3;
  public static final int EXCLAMATION = 28;
  public static final int AMPERSAND = 15;
  public static final int EOF = 0;
  public static final int BOOLLITERAL = 36;
  public static final int error = 1;
  public static final int CLOSEBRACKET = 12;
  public static final int PERCENT = 31;
  public static final int VOID = 5;
  public static final int INTLITERAL = 35;
  public static final int ELSE = 4;
  public static final int OPENBRACKET = 11;
  public static final int WHILE = 6;
  public static final int CLOSEBRACE = 10;
  public static final int GREATERTHANEQUALS = 25;
  public static final int OPENBRACE = 9;
  public static final int EXCLAMATIONEQUALS = 27;
  public static final int AMPERSANDAMPERSAND = 18;
  public static final int DO = 2;
  public static final int IDENTIFIER = 34;
}

